sudo: false
language: php
php:
  - 5.6
services:
  - mysql
matrix:
  allow_failures:
    - php: hhvm
before_script:
#  - composer config -g github-oauth.github.com
  - mysql -e "create database IF NOT EXISTS symfony;" -uroot
  - composer install --no-interaction

script:
  - vendor/phpunit --coverage-clover=coveralls.clover
