basket_planner_match_homepage:
    path:     /
    defaults: { _controller: BasketPlannerMatchBundle:Match:index }

basket_planner_match_create:
    path:     /create
    defaults: { _controller: BasketPlannerMatchBundle:Match:create }

basket_planner_match_show:
    path:     /show
    defaults: { _controller: BasketPlannerMatchBundle:Match:show }

basket_planner_match_join:
    path:     /join
    defaults: { _controller: BasketPlannerMatchBundle:Match:join }

basket_planner_match_cancel:
    path:     /cancel
    defaults: { _controller: BasketPlannerMatchBundle:Match:cancel }
