basket_planner_match_create:
    path:     /create
    defaults: { _controller: BasketPlannerMatchBundle:Match:create }
basket_planner_match_show:
    path:     /show
    defaults: { _controller: BasketPlannerMatchBundle:Match:show }