parameters:

services:
    basketplanner_match.map_extension:
        class: BasketPlanner\MatchBundle\Extension\MyGoogleMapExtension

    basketplanner_match.map_loader_service:
        class: BasketPlanner\MatchBundle\Services\GoogleMapLoaderService
        arguments:
            map: "@ivory_google_map.map="
            mapEvent: "@ivory_google_map.event="
            entityManager: "@doctrine.orm.entity_manager"

    basketplanner_match.user_activity_service:
        class: BasketPlanner\MatchBundle\Services\UserMatchActivityService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    basketplanner_match.match_loader_service:
        class: BasketPlanner\MatchBundle\Services\MatchLoaderService
        arguments:
            em: "@doctrine.orm.entity_manager"
            formFactory: "@form.factory"
            paginator: "@knp_paginator"