basket_planer_main:
    resource: "@BasketPlanerMainBundle/Resources/config/routing.yml"
    prefix:   /

basket_planer_team:
    resource: "@BasketPlanerTeamBundle/Resources/config/routing.yml"
    prefix:   /team

basket_planer_match:
    resource: "@BasketPlanerMatchBundle/Resources/config/routing.yml"
    prefix:   /match

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

custom_login:
    path: /login/check-custom
