basket_planer_main:
    resource: "@BasketPlanerMainBundle/Resources/config/routing.yml"
    prefix:   /

basket_planer_team:
    resource: "@BasketPlanerTeamBundle/Resources/config/routing.yml"
    prefix:   /

basket_planer_match:
    resource: "@BasketPlanerMatchBundle/Resources/config/routing.yml"
    prefix:   /

nfq_home:
    resource: "@NFQHomeBundle/Resources/config/routing.yml"
    prefix:   /
