basket_planner_match:
    resource: "@BasketPlannerMatchBundle/Resources/config/routing.yml"
    prefix:   /match

basket_planner_team:
    resource: "@BasketPlannerTeamBundle/Resources/config/routing.yml"
    prefix:   /team

basket_planner_main:
    resource: "@BasketPlannerMainBundle/Resources/config/routing.yml"
    prefix:   /

basket_planner_user:
    resource: "@BasketPlannerUserBundle/Resources/config/routing.yml"
    prefix:   /user

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

custom_login:
    path: /login/check-custom
