basket_planner_team_homepage:
    path:     /
    defaults: { _controller: BasketPlannerTeamBundle:Team:index }

basket_planner_team.create:
    path:     /create
    defaults: { _controller: BasketPlannerTeamBundle:Team:create }
    methods: [GET, POST]

basket_planner_team.show:
    path:     /show/{id}
    defaults: { _controller: BasketPlannerTeamBundle:Team:show }
    methods: [GET]
    requirements:
        id: \d+

basket_planner_team.search:
   path: /search-user
   defaults: { _controller: BasketPlannerTeamBundle:Team:search }

basket_planner_team.leave:
   path: /leave
   defaults: { _controller: BasketPlannerTeamBundle:Team:leave }

basket_planner_team.delete:
   path: /delete
   defaults: { _controller: BasketPlannerTeamBundle:Team:delete }

basket_planner_team.invite.create:
   path: /invite-create
   defaults: { _controller: BasketPlannerTeamBundle:Team:invite }

basket_planner_team.invite.delete:
   path: /invite-delete
   defaults: { _controller: BasketPlannerTeamBundle:Team:inviteDelete }

basket_planner_team.invite.accept:
   path: /invite-accept
   defaults: { _controller: BasketPlannerTeamBundle:Team:inviteAccept }

basket_planner_team.invite.changeStatus:
   path: /invite-change-status
   defaults: { _controller: BasketPlannerTeamBundle:Team:inviteChangeStatus }