basket_planner_team_homepage:
    path:     /
    defaults: { _controller: BasketPlannerTeamBundle:Team:index }

basket_planner_team.create:
    path:     /create
    defaults: { _controller: BasketPlannerTeamBundle:Team:create }
    methods: [GET, POST]

basket_planner_team_show:
    path:     /show/{id}
    defaults: { _controller: BasketPlannerTeamBundle:Team:show }
    methods: [GET]
    requirements:
        id: \d+

basket_planner_team.search:
   path: /search-user
   defaults: { _controller: BasketPlannerTeamBundle:Team:search }

basket_planner_team.invite.create:
   path: /create-invite
   defaults: { _controller: BasketPlannerTeamBundle:Team:invite }