basket_planner_team_homepage:
    path:     /
    defaults: { _controller: BasketPlannerTeamBundle:Team:index }

basket_planner_team_create:
    path:     /create
    defaults: { _controller: BasketPlannerTeamBundle:Team:create }
    methods: [GET, POST]

basket_planner_team_show:
    path:     /show/{id}
    defaults: { _controller: BasketPlannerTeamBundle:Team:show }
    methods: [GET]
    requirements:
        id: \d+