services:
#    basket_planner_team.example:
#        class: BasketPlanner\Bundle\TeamBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    basketplanner_team.team_manager:
        class: BasketPlanner\TeamBundle\Service\TeamManager
        arguments:
            entityManager: "@doctrine.orm.entity_manager"