basket_planner_user_profile:
   path: /{id}
   defaults: { _controller: BasketPlannerUserBundle:Profile:show }
   methods: [GET]
   requirements:
       id: \d+

basket_planner_user_notification:
   path: /notifications/{page}
   defaults: { _controller: BasketPlannerUserBundle:Notification:show, page: 1 }
   methods: [GET]
   requirements:
      page: \d+

basket_planner_user_notification.delete:
   path: /notifications/delete
   defaults: { _controller: BasketPlannerUserBundle:Notification:delete }

basket_planner_user_notification.update_status:
   path: /notifications/update-status
   defaults: { _controller: BasketPlannerUserBundle:Notification:updateStatus }