basket_planner_user_profile:
   path: /{id}
   defaults: { _controller: BasketPlannerUserBundle:Profile:show }
   methods: [GET]
   requirements:
       id: \d+

basket_planner_user_notification:
   path: /notifications/{page}
   defaults: { _controller: BasketPlannerUserBundle:Notification:show, page: 1 }
   methods: [GET]
   requirements:
      page: \d+