parameters:
    basketplanner_user_provider.class: BasketPlanner\UserBundle\Security\User\OAuthUserProvider

services:
    basketplanner_user_provider:
        class: "%basketplanner_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager, {facebook: facebookId, google: googleId}, @event_dispatcher]

    basketplanner_form_registration:
        class: BasketPlanner\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: basketplanner_user_registration }

    basketplanner.profile.form.type:
        class: BasketPlanner\UserBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: basketplanner_user_profile }

    basketplanner.user.event_listener:
        class: BasketPlanner\UserBundle\Listeners\UserEventsListener
        arguments:
            templating: "@twig"
            mailer: "@mailer"
        tags:
        - { name: kernel.event_listener, event: registration.event, method: onRegistrationEvent }