parameters:
    basketplanner_user.provider.class: BasketPlanner\UserBundle\Security\User\OAuthUserProvider

services:
    basketplanner_user.provider:
        class: "%basketplanner_user.provider.class%"
        arguments: [@fos_user.user_manager, {facebook: facebookId, google: googleId}, @event_dispatcher]

    basketplanner_user.form.registration:
        class: BasketPlanner\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: basketplanner_user_form_registration }

    basketplanner_user.form.profile:
        class: BasketPlanner\UserBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: basketplanner_user_form_profile }

    basketplanner_user.event_listener:
        class: BasketPlanner\UserBundle\Listeners\UserEventsListener
        arguments:
            templating: "@twig"
            mailer: "@mailer"
        tags:
        - { name: kernel.event_listener, event: registration.event, method: onRegistrationEvent }