parameters:
    basketplanner_user.provider.class: BasketPlanner\UserBundle\Security\User\OAuthUserProvider

services:
    basketplanner_user.provider:
        class: "%basketplanner_user.provider.class%"
        arguments: [@fos_user.user_manager, {facebook: facebookId, google: googleId}, @basketplanner_user.notifications_service]

    basketplanner_user.form.registration:
        class: BasketPlanner\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: basketplanner_user_form_registration }

    basketplanner_user.form.profile:
        class: BasketPlanner\UserBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: basketplanner_user_form_profile }

    basketplanner_user.send_email_service:
        class: BasketPlanner\UserBundle\Consumer\SendEmailConsumer
        arguments:
            mailer: "@mailer"
            logger: "@logger"

    basketplanner_user.notification_consumer_service:
        class: BasketPlanner\UserBundle\Consumer\NotificationConsumer
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            logger: "@logger"

    basketplanner_user.notifications_service:
        class: BasketPlanner\UserBundle\Service\NotificationService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            emailProducer: "@old_sound_rabbit_mq.send_email_producer"
            notificationsProducer: "@old_sound_rabbit_mq.notifications_producer"
            router: "@router"

